### ISSUE TITLE
Add .ssh/config

### ISSUE THREAD

**Issue by hinerm** [ctrueden/dotfiles#5]
`machines.sh` aliases shell commands that assume a `.ssh/config` is in place.. but I couldn't find an appropriate `.ssh/config`

**Comment by ctrueden** [comment]
Can't add it, because it has secrets, and is also user-specific. And you [can't include one SSH config in another](http://superuser.com/a/247572), unfortunately.

I avoided the issue in 6b8ec0f75554f2d25d531a43aa8e962ae1c613a5 by making the aliases more explicit about the machines to which they connect.

**Comment by ctrueden** [comment]
Years later, you now *can* `Include` SSH config files. So I did it with 31f689c75b416ddd2500d6e34b2bc9735f10f507.
